"""
Django settings for A project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DATA_UPLOAD_MAX_MEMORY_SIZE = 4 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 4 * 1024 * 1024
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-aulc-jfas0wyc2ya3vmi1!4njr_ai(mq+o8z-!huzpmkuc(&r8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = []

SITE_ID = 1 
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #-----
    'django.contrib.sitemaps',
    'django.contrib.sites',
    # my_apps
    'home.apps.HomeConfig',
    'accounts.apps.AccountsConfig',
    'products.apps.ProductsConfig',
    'orders.apps.OrdersConfig',
    'ckeditor',

    #third-part apps
    'storages',
    'django_celery_beat', # python manage.py migrate
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'A.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'orders.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'A.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'your database_name',
        'USER': 'postgres',
        'PASSWORD': 'guest',
        'HOST':'127.0.0.1',
        'PORT':'5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


AUTH_USER_MODEL = 'accounts.User'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'# if user want to see this , server find this address
MEDIA_ROOT = BASE_DIR / 'media' #if user want to upload, uploaded this address

#pip install django-storages and boto3
# ARVAN CLOUD OBJECT STORAGES

AWS_SERVICE_NAME = 's3'
AWS_ACCESS_KEY_ID = 'a6cca2b7-d75b-4c7b-9259-7c5008b39e91'
AWS_SECRET_ACCESS_KEY = ''
AWS_S3_ENDPOINT_URL = 'https://s3.ir-tbz-sh1.arvanstorage.ir'
AWS_BUCKET_NAME = 'asfsafgerge'
AWS_LOCAL_STORAGE = f"{BASE_DIR}/aws/"


STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS':{
            'access_key': AWS_ACCESS_KEY_ID,
            'secret_key': AWS_SECRET_ACCESS_KEY,
            'endpoint_url': AWS_S3_ENDPOINT_URL,
            'bucket_name': AWS_BUCKET_NAME,
            'file_overwrite': False,
        }

    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'#don't change , default django
    },
}
#in the real project we upload media in different server(cloud) because own project has heavy




# zarin pal api 
ZP_API_REQUEST = 'https://payment.zarinpal.com/pg/v4/payment/request.json' #ارسال اطلاعات  
ZP_API_VERIFY = 'https://payment.zarinpal.com/pg/v4/payment/verify.json'
ZP_MERCHANT_ID = 'your merchant id on your panel'

#CKEDITOR
CKEDITOR_CONFIGS = {
    'default':{
        'toolbar':'full'
    }
}
#GOOGLE APP PASSWORD
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_HOST_PASSWORD = 'your password that google give you'
EMAIL_HOST_USER = 'ali@gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True


#LOGGING
LOGGING = {
    'version':1,
    'disable_existing_loggers': False,#logger default django
    'formatters':{
        'verbose':{
            'format':'{name} {levelname} {asctime} {module} {message}',
            'style':'{',
        },
        'simple':{
            'format':'{levelname} {message}',
            'style': '{',
        }
    },
    'handlers':{
        'file':{
            'class':'logging.FileHandler',
            'filename':'logs/general.log',
            'level':'DEBUG',
            'formatter': 'verbose'
        },
        'console':{
            'class':'logging.StreamHandler',
        },
        'file_rotate':{
            'class':'logging.handlers.RotatingFileHandler',
            'filename': 'logs/app.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
        },
    },
    'loggers':{
        'new':{
            'level':'DEBUG',
            'handlers': ['file']
        },
        'accounts':{
            'level':'INFO',
            'handlers': ['file']
        }
    }

}

CACHES = {
    'default':{
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379'
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'